[workspace]
members = [
  "src/aws",
  "src/init",
  "src/system",
  "src/host-proxy"
, "src/nautilus_host_proxy"]

exclude = [
  "src/nautilus-server"
]

# Set default resolver to version 2
resolver = "2" 
