[package]
name = "nautilus_host_proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
http = "1.3.1"
hyper = { version = "0.14", features = ["full"] }
log = "0.4.28"
tokio = { version = "1.48.0", features = ["full"] }
anyhow = "1"